'use client';

import { TrendingUp, TrendingDown, Minus, AlertTriangle, ShieldCheck, AlertOctagon } from 'lucide-react';
import type { GeoEvent, TrendSignal, TenantRisk } from '@/types/report';

const DEFAULT_EVENTS: GeoEvent[] = [
  {
    id: 'rempang',
    title: 'Rempang Island MOU — US × Indonesia',
    description: 'Memorandum of Understanding signed between the United States and Indonesia for strategic development of Rempang Island, directly adjacent to Batam FTZ. Positions Batam as the anchor of a wider US-aligned Indo-Pacific industrial corridor.',
    source: 'Ministry of Investment, Apr 2026',
    impact: { fdi: 'improving', gdp: 'improving', tenantRisk: 'neutral' },
  },
  {
    id: 'carbon_neutral',
    title: 'Carbon Neutral Industrial Park — Panbil & Sembcorp',
    description: 'Agreement between President Prabowo and Singapore PM Wong to establish a Carbon Neutral Industrial Park in Batam, co-developed by Panbil Group and Sembcorp Industries. Targets ESG-compliant manufacturing tenants.',
    source: 'BP Batam, Mar 2026',
    impact: { fdi: 'improving', gdp: 'improving', tenantRisk: 'neutral' },
  },
  {
    id: 'solar_offtake',
    title: 'Singapore Green Energy Offtake (Solar)',
    description: 'Singapore–Indonesia energy agreement enabling Singapore to offtake renewable energy generated by solar farms in Batam via the Batam–SGP Green Corridor project. Nusa Solar and Haitai Solar are key suppliers.',
    source: 'EMA Singapore / MEMR Indonesia, Q1 2026',
    impact: { fdi: 'improving', gdp: 'stable', tenantRisk: 'neutral' },
  },
  {
    id: 'us_idn_fta',
    title: 'US–Indonesia Trade Framework — 100+ HS Code Exemptions',
    description: 'Active negotiations on over 100 HS code exemptions (machinery & aeronautics) within US–Indonesia bilateral trade discussions. Potential to significantly boost electronics and aerospace component exports from Batam.',
    source: 'USTR / Kemendag, Q2 2026',
    impact: { fdi: 'improving', gdp: 'improving', tenantRisk: 'neutral' },
  },
];

function SignalBadge({ signal }: { signal: TrendSignal }) {
  if (signal === 'improving') {
    return (
      <span className="inline-flex items-center gap-1 bg-emerald-500/15 text-emerald-400 text-xs font-semibold px-2 py-1 rounded-full">
        <TrendingUp size={11} /> Improving
      </span>
    );
  }
  if (signal === 'declining') {
    return (
      <span className="inline-flex items-center gap-1 bg-red-500/15 text-red-400 text-xs font-semibold px-2 py-1 rounded-full">
        <TrendingDown size={11} /> Declining
      </span>
    );
  }
  return (
    <span className="inline-flex items-center gap-1 bg-slate-700/60 text-slate-400 text-xs font-semibold px-2 py-1 rounded-full">
      <Minus size={11} /> Stable
    </span>
  );
}

function RiskBadge({ risk }: { risk: TenantRisk }) {
  if (risk === 'red') {
    return (
      <span className="inline-flex items-center gap-1 bg-red-500/15 text-red-400 text-xs font-semibold px-2 py-1 rounded-full">
        <AlertOctagon size={11} /> High Risk
      </span>
    );
  }
  if (risk === 'risk') {
    return (
      <span className="inline-flex items-center gap-1 bg-amber-500/15 text-amber-400 text-xs font-semibold px-2 py-1 rounded-full">
        <AlertTriangle size={11} /> Monitor
      </span>
    );
  }
  return (
    <span className="inline-flex items-center gap-1 bg-slate-700/60 text-slate-400 text-xs font-semibold px-2 py-1 rounded-full">
      <ShieldCheck size={11} /> Neutral
    </span>
  );
}

export default function GeoSection({ events = DEFAULT_EVENTS }: { events?: GeoEvent[] }) {
  return (
    <div className="space-y-4">
      {events.map((event) => (
        <div
          key={event.id}
          className="border border-slate-800 bg-slate-800/20 hover:bg-slate-800/40 rounded-xl p-5 transition-colors"
        >
          {/* Title + source */}
          <div className="flex items-start justify-between gap-3 mb-2">
            <h4 className="text-sm font-bold text-slate-100 leading-snug">{event.title}</h4>
            {event.source && (
              <span className="shrink-0 text-xs text-slate-500 italic">{event.source}</span>
            )}
          </div>

          {/* Description */}
          <p className="text-xs text-slate-400 leading-relaxed mb-4">{event.description}</p>

          {/* Impact Matrix */}
          <div className="flex flex-wrap items-center gap-3 pt-3 border-t border-slate-800">
            <span className="text-xs text-slate-500 font-medium mr-1">Impact:</span>
            <div className="flex items-center gap-1.5">
              <span className="text-xs text-slate-500">FDI</span>
              <SignalBadge signal={event.impact.fdi} />
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-xs text-slate-500">GDP</span>
              <SignalBadge signal={event.impact.gdp} />
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-xs text-slate-500">Tenant Risk</span>
              <RiskBadge risk={event.impact.tenantRisk} />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
